--CLIENTES--

--CANTIDAD DE CLIENTES POR PROVINCIA--

SELECT Provincia, COUNT(Cliente) AS CANTIDADDECLIENTES
FROM CLIENTES
GROUP BY Provincia
ORDER BY CANTIDADDECLIENTES DESC;

--CANTIDAD DE CLIENTES POR SEGMENTO--

SELECT Segmento,COUNT(Cliente) AS CANTIDADDECLIENTES
FROM CLIENTES
GROUP BY Segmento
ORDER BY CANTIDADDECLIENTES DESC;

--CLIENTES POR SEGMENTO Y PROVINCIA--

SELECT Segmento,Provincia,COUNT(Cliente) AS CANTIDADDECLIENTES
FROM CLIENTES
GROUP BY Segmento,Provincia
ORDER BY CANTIDADDECLIENTES DESC;

--INFORMACION DE CONTACTOS POR CLIENTES--
SELECT Cliente,Email,Telefono
FROM CLIENTES;

--CLIENTES SIN INFORMACION DE CONTACTO--

SELECT Cliente,Email
FROM CLIENTES
WHERE (Email is null or Email='');

select Cliente, Telefono
from CLIENTES
where (Telefono is null or Telefono='');

--PRODUCTOS--

--CANTIDAD DE PRODUCTOS EXISTENTES--

SELECT COUNT(*)
FROM PRODUCTOS;

--TIPOS DE CATEGORIA Y PRODUCTOS--

SELECT CategoriaID,Categoria
FROM CATEGORIAS;

SELECT CategoriaID,COUNT(Producto) AS CANTIDAD
FROM PRODUCTOS
GROUP BY CategoriaID
ORDER BY CANTIDAD DESC;

--CANTIDAD DE PRODUCTOS POR SUBCATEGORIAS--

SELECT Subcategoria
FROM PRODUCTOS;

SELECT Subcategoria, COUNT(Producto) as cantidaddeproductos
FROM PRODUCTOS
group by Subcategoria
order by cantidaddeproductos desc;


--CANTIDAD DE PRODUCTOS POR MARCA--

 SELECT DISTINCT Marca
FROM PRODUCTOS
ORDER BY Marca ASC;

SELECT Marca,COUNT(Marca) as cantidad
FROM PRODUCTOS
group by Marca
order by Marca ASC;

--COSTOS PRODUCTOS--

--COSTO MAS BAJO--

SELECT Producto	,CostoUnitario,Marca 
FROM PRODUCTOS
WHERE CostoUnitario=(SELECT MIN(CostoUnitario) FROM PRODUCTOS);

--COSTO MAS ALTO--

SELECT Producto,CostoUnitario,Marca
FROM PRODUCTOS
WHERE CostoUnitario= (SELECT MAX(CostoUnitario) FROM PRODUCTOS);

SELECT Producto,CostoUnitario
FROM PRODUCTOS
ORDER BY CostoUnitario DESC;

--PRECIOS DE LISTA DE PRODUCTOS--

SELECT Producto,PrecioLista,Marca
FROM PRODUCTOS
ORDER BY PrecioLista DESC;

--PRECIO DE LISTA MAS ALTO Y MENOR

SELECT Producto,PrecioLista,Marca
FROM PRODUCTOS
WHERE PrecioLista= (SELECT MIN(PrecioLista) FROM PRODUCTOS)OR  PrecioLista=(SELECT MAX(PrecioLista) FROM PRODUCTOS);

--COSTO PROMEDIO--
SELECT AVG(CostoUnitario) AS COSTOPROMEDIO
FROM PRODUCTOS;

--
--COSTO PROMEDIO POR MARCA--

SELECT Marca,AVG(CostoUnitario) AS COSTOPRMEDIOPORMARCA
FROM PRODUCTOS
GROUP BY Marca
ORDER BY COSTOPRMEDIOPORMARCA DESC;

--COSTO PROMEDIO POR CATEGORIAS--

SELECT CategoriaID,AVG(CostoUnitario)AS COSTOPROMPORCATEGORIA
FROM PRODUCTOS
GROUP BY CategoriaID
ORDER BY COSTOPROMPORCATEGORIA DESC;

--MARGEN 

SELECT  Producto,Marca,PrecioLista/CostoUnitario AS MARGEN
FROM PRODUCTOS
ORDER BY MARGEN DESC;

--VENDEDORES--

SELECT *
FROM VENDEDORES;

--CANTIDAD DE VENDEDORES POR SUCURSAL--

SELECT SucursalID,Supervisor
FROM VENDEDORES;

SELECT SucursalID, COUNT (Vendedor) AS VENDEDORESXSUCURSAL
FROM VENDEDORES
GROUP BY SucursalID;

SELECT Supervisor,COUNT(SucursalID) AS VENDEDORESACARGO
FROM VENDEDORES
GROUP BY Supervisor;

SELECT Supervisor,SucursalID,Vendedor
FROM VENDEDORES;

--VENTAS--

--VENTAS REALIZADAS EN  2025--

select count(ventaid) AS TOTAL_VENTAS_2025
from VENTAS
WHERE YEAR (Fecha)=2025;

SELECT SucursalID,COUNT(VentaID) AS VENTAS_DE_2025_POR_SUCURSAL
FROM VENTAS
WHERE YEAR(Fecha)=2025
GROUP BY SucursalID
ORDER BY VENTAS_DE_2025_POR_SUCURSAL DESC
;

SELECT MedioPago,COUNT(VentaID) AS VENTAS_POR_MODALIDAD_DE_PAGO
FROM VENTAS
WHERE YEAR(Fecha)=2025
GROUP BY MedioPago
ORDER BY VENTAS_POR_MODALIDAD_DE_PAGO DESC;


SELECT CanalVenta ,COUNT(VentaID) AS VENTAS_POR_CANAL_DE_VENTA
FROM VENTAS
WHERE YEAR(Fecha)=2025
GROUP BY CanalVenta
ORDER BY VENTAS_POR_CANAL_DE_VENTA DESC;

SELECT VendedorID,COUNT(VentaID) AS CANTIDAD_DE_VENTAS_POR_VENDEDOR
FROM VENTAS
WHERE YEAR(Fecha)= 2025
GROUP BY VendedorID
ORDER BY  CANTIDAD_DE_VENTAS_POR_VENDEDOR DESC;

--VENTAS REALIZADAS EN 2026--

SELECT COUNT(VentaID) AS VENTAS_TOTALES_2026
FROM VENTAS
WHERE YEAR(Fecha)= 2026;

SELECT SucursalID,COUNT(VentaID) AS VENTAS_POR_SUCURSAL_2026
FROM VENTAS
WHERE YEAR(Fecha)=2026
GROUP BY SucursalID
ORDER BY VENTAS_POR_SUCURSAL_2026 DESC;

SELECT MedioPago,COUNT(VentaID) AS VENTAS_POR_MEDIO_DE_PAGO
FROM VENTAS
WHERE YEAR(Fecha)=2026
GROUP BY MedioPago
ORDER BY VENTAS_POR_MEDIO_DE_PAGO DESC;













